[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/mmm"]

[programs.localnet]
mmm = "mmm3XBJg5gk8XJxEKBvdgptZz6SgK4tXvn36sodowMc"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.spec.ts"
