[workspace]
members = ["programs/*"]

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = true

[profile.release]
overflow-checks = true
strip = true
opt-level = "z"
lto = true

[profile.release.build-override]
opt-level = "z" 
incremental = false
codegen-units = 1