name: publish_npm
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build:
    environment: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd sdk
          npm ci
          npm run build
          npm publish --access public
