name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  solana_version: 1.14.3
  anchor_version: 0.25.0

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: metadaobuilders/anchor-test@v1
        with:
          anchor-version: '0.25.0'
          solana-cli-version: '1.14.3'
          node-version: '16.15.1'
